// react/src/components/carousel/index.jsx
import React, { Component } from "react";
// import {Route, Switch, BrowserRouter as Router} from 'react-router-dom';
// import Test from "../../views/Test";
import "./index.scss";
import PropTypes from "prop-types";
// 当props为对象时候, 不能直接输出、不能直接修改, 否则报错
export default class Carousel extends Component {
  constructor(props) {
    super(props);
    this.state = {
      index: 0,
      listIndex: 1,
      translateX: 0,
      transition: true,
      itemsLen: 0,
      list: [],
      listLen: 0,
      timer: 0,
      intervalTimer: 0
    };
    this.initList = this.initList.bind(this);
    this.$emit = this.$emit.bind(this);
    this.changeView = this.changeView.bind(this);
    this.autoPlay = this.autoPlay.bind(this);
    this.clearPlay = this.clearPlay.bind(this);
    this.handlerIndex = this.handlerIndex.bind(this);
    this.handlerDir = this.handlerDir.bind(this);

  }

  static propTypes = {
    items: PropTypes.array.isRequired,
    interval: PropTypes.number,
    width: PropTypes.string,
    height: PropTypes.string,
    auto: PropTypes.bool,
    autoInterval: PropTypes.number,
    hideDir: PropTypes.bool,
    isReloadPlay: PropTypes.bool,
    clickEach: PropTypes.bool,
    onchange: PropTypes.func
  };
  static defaultProps = {
    width: "800px",
    height: "450px",
    interval: 500,
    auto: true,
    autoInterval: 5000,
    hideDir: true,
    isReloadPlay: false,
    clickEach: true,
    onchange: () => {},
    title: () => {},
    count: () => {}
  };

  initList() {
    const props = this.props;
    let itemsLen = props.items.length - 1;
    let list = [props.items[itemsLen], ...props.items, props.items[0]];
    let listIndex = this.state.listIndex;
    this.setState(
      {
        itemsLen,
        list,
        listLen: list.length,
        translateX: listIndex * -800,
        index: 0,
        listIndex: 1
      },
      () => {
        this.autoPlay();
      }
    );
  }
  componentDidMount() {
    this.initList();
    // $nextTick
    // 方法会在组件已经被渲染到 DOM 中后运行   - 挂载
  }
  componentWillUnmount() {
    // 卸载触发
  }
  $emit(event, msg) {
    if (!event && event !== 0) return new Error("event不能为空");
    return this.props[event](msg);
  }
  changeView(index, oldIndex) {
    const state = this.state;
    let transition = true;
    let translateX = 0;
    let timer = 0;
    if (oldIndex === 0 && index !== 1 && index !== index - oldIndex) {
      timer = setTimeout(() => {
        transition = false;
        translateX = -(index + 1) * 800;
        this.setState({
          transition,
          translateX
        });
      }, 500);
    } else if (oldIndex === state.itemsLen && index === 0) {
      translateX = -(state.listLen - 1) * 800;
      timer = setTimeout(() => {
        transition = false;
        translateX = -1 * 800;
        this.setState({
          transition,
          translateX
        });
      }, 500);
    } else {
      translateX = (index + 1) * -800;
    }
    this.setState(
      {
        transition,
        translateX,
        timer
      },
      () => {
        this.$emit("onchange", index);
      }
    );
  }
  autoPlay() {
    this.clearPlay();
    if (this.props.auto) {
      this.setState({
        intervalTimer: setInterval(() => {
          const state = this.state;
          let oldIndex = state.index;
          let index = oldIndex;
          index = index >= state.itemsLen ? 0 : ++index;
          this.setState(
            {
              index
            },
            () => {
              this.changeView(index, oldIndex);
            }
          );
        }, this.props.autoInterval)
      });
    }
  }
  clearPlay() {
    clearInterval(this.state.intervalTimer);
  }
  handlerIndex(index) {
    let oldIndex = this.state.index;
    this.setState(
      {
        index
      },
      () => {
        this.changeView(index, oldIndex);
      }
    );
  }
  handlerDir(dir) {
    const state = this.state;
    let oldIndex = state.index;
    let index = oldIndex;
    if (dir === "next") {
      index = index === state.itemsLen ? 0 : ++index;
    } else {
      index = index <= 0 ? state.itemsLen : --index;
    }
    this.setState(
      {
        index
      },
      () => {
        this.changeView(index, oldIndex);
      }
    );
  }
  render() {
    const state = this.state;
    const props = this.props;
    return (
      <section className="wrap">
        <div
          style={{
            width: props.width,
            height: props.height,
            overflow: "hidden"
          }}
        >
          <div
            className="carousel-img"
            style={{
              width: state.listLen * 100 + "%",
              transform: `translateX(${state.translateX}px)`,
              transition: state.transition
                ? `all ${props.interval / 1000}s ease`
                : ""
            }}
          >
            {state.list.map((item, index) => (
              // 这里有个slot
              <div
                className="item"
                key={index}
                style={{
                  background: `url(${item.src}) no-repeat center center/100% 100%`,
                  color: "#fff"
                }}
              >
                {this.props.title(item.title)}
              </div>
            ))}
          </div>
          <div
            className="wrap-btn"
            onMouseEnter={this.clearPlay.bind(this)}
            onMouseLeave={this.autoPlay.bind(this)}
            onClick={this.$emit("onchange", this.state.index)}
          >
            <div style={{ flex: 1 }} />
            {props.hideDir ? (
              <div className="carouse-btn-direction" v-if="!">
                <p onClick={this.handlerDir.bind(this, "prev")}>&lt;</p>
                <p onClick={this.handlerDir.bind(this, "next")}>&gt;</p>
              </div>
            ) : (
              ""
            )}
            <div style={{ flex: 1 }} />
            <div className="carouse-btn">
              <section>
                <p style={{ flex: 1 }} />
                {props.clickEach ? (
                  <div style={{ display: "flex" }}>
                    {new Array(state.itemsLen + 1)
                      .fill("x")
                      .map((item, index) => (
                        <span
                          key={index * 100}
                          className={[index === state.index ? "active" : ""]}
                          onClick={this.handlerIndex.bind(this, index)}
                        />
                      ))}
                  </div>
                ) : (
                  ""
                )}
                <p style={{ flex: 1 }} />
                {this.props.count({
                  currentIndex: state.index,
                  total: state.itemsLen
                })}
              </section>
            </div>
          </div>
        </div>
      </section>
    );
  }
}

// vue/src/components/carousel/index.vue
<template>
  <section class="wrap">
    <div :style="{ width, height, overflow: 'hidden' }">
      <div
        class="carousel-img"
        :style="{
          width: listLen * 100 + '%',
          transform: `translateX(${tranlateX}px)`,
          transition: transition ? `all ${interval / 1000}s ease` : ''
        }"
      >
        <div
          class="item"
          v-for="(item, index) of list"
          :key="index"
          :style="{
            background: `url(${item.src}) no-repeat center center/100% 100%`,
            color: '#fff'
          }"
        >
          <slot name="title" :title="item.title"></slot>
        </div>
      </div>
    </div>
    <div
      class="wrap-btn"
      @mouseenter="clearPlay"
      @mouseleave="autoPlay"
      @click="$emit('imgs', index)"
    >
      <div style="flex: 1"></div>
      <div class="carouse-btn-directon" v-if="!hideDir">
        <p @click.stop="runDirection">&lt;</p>
        <p @click.stop="runDirection('add')">&gt;</p>
      </div>
      <div style="flex: 1"></div>
      <div class="carouse-btn">
        <section>
          <p style="flex: 1"></p>
          <template v-if="clickEach">
            <span
              v-for="i of itemsLen + 1"
              :key="i * 2"
              :class="[i === index + 1 ? 'active' : '']"
              @click.stop="index = i - 1"
            ></span>
          </template>
          <p style="flex: 1"></p>
          <slot name="count" :count="{ index, total: itemsLen + 1 }"></slot>
        </section>
      </div>
    </div>
    <div class="carouse-slider"></div>
  </section>
</template>

<script>
export default {
  data() {
    return {
      index: 0,
      listIndex: 1,
      tranlateX: 0,
      transition: true,
      itemsLen: 0,
      list: [],
      listLen: 0,
      timer: 0,
      intervalTimer: 0
    };
  },
  props: {
    width: {
      type: String,
      default: "800px"
    },
    height: {
      type: String,
      default: "450px"
    },
    items: {
      type: Array,
      required: true
    },
    interval: {
      type: Number,
      default: 500
    },
    auto: {
      type: Boolean,
      default: true
    },
    autoInterval: {
      type: Number,
      default: 5000
    },
    hideDir: {
      type: Boolean,
      default: false
    },
    isReloadPlay: {
      type: Boolean,
      default: false
    },
    clickEach: {
      type: Boolean,
      default: true
    }
  },
  created() {
    this.initList();
  },
  watch: {
    index(index, oldIndex) {
      this.$emit("change", index);
      this.transition = true;
      if (oldIndex === 0 && index !== 1 && index !== index - oldIndex) {
        this.tranlateX = 0;
        this.timer = setTimeout(() => {
          this.transition = false;
          this.tranlateX = -(index + 1) * 800;
        }, 500);
      } else if (oldIndex === this.itemsLen && index === 0) {
        this.tranlateX = -(this.listLen - 1) * 800;
        this.timer = setTimeout(() => {
          this.transition = false;
          this.tranlateX = -1 * 800;
        }, 500);
      } else {
        this.tranlateX = (index + 1) * -800;
      }
    },
    items: {
      hanlder() {
        if (this.isReloadPlay) {
          this.initList();
        }
      },
      deep: true
    }
  },
  methods: {
    initList() {
      this.itemsLen = this.items.length - 1;
      this.list = [this.items[this.itemsLen], ...this.items, this.items[0]];
      this.listLen = this.list.length;
      this.tranlateX = this.listIndex * -800;
      this.index = 0;
      this.listIndex = 1;
    },
    runDirection(add) {
      if (add === "add") {
        this.index = this.index >= this.itemsLen ? 0 : ++this.index;
      } else {
        this.index = this.index <= 0 ? this.itemsLen : --this.index;
      }
    },
    autoPlay() {
      this.clearPlay();
      if (this.auto) {
        this.intervalTimer = setInterval(() => {
          this.index = this.index >= this.itemsLen ? 0 : ++this.index;
        }, this.autoInterval);
      }
    },
    clearPlay() {
      clearInterval(this.intervalTimer);
    }
  },
  mounted() {
    this.$nextTick(() => {
      this.autoPlay();
    });
  }
};
</script>

<style lang="scss" scoped>
.wrap {
  position: relative;
  flex-direction: column;
  .carousel-img {
    display: flex;
    height: 100%;
    .item {
      position: relative;
      width: 800px;
      height: 100%;
    }
  }
  .wrap-btn {
    display: flex;
    flex-direction: column;
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    .carouse-btn {
      width: 100%;
      align-self: center;
      section {
        display: flex;
        position: relative;
        justify-content: center;
        align-items: flex-end;
        padding: 20px 0;
        span {
          width: 20px;
          height: 20px;
          border-radius: 50%;
          background: grey;
          margin-right: 5px;
          cursor: pointer;
        }
        .active {
          background: red;
        }
      }
    }
    .carouse-btn-directon {
      display: inherit;
      justify-content: space-between;
      margin-top: 100px;
      p:nth-child(2) {
        align-self: end;
      }
      p {
        width: 100px;
        height: 100px;
        background: rgba(0, 0, 0, 0.5);
        color: #fff;
        font-size: 35px;
        line-height: 2.9;
        text-align: center;
        cursor: pointer;
      }
    }
  }
}
p {
  margin: 0;
}
</style>
