// react/src/components/carousel-slider/index.jsx
import React from "./node_modules/react";
import "./index.scss";
import propTypes from "./node_modules/prop-types";
export default class CarouselSlider extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      index: 0,
      wrapWidth: 0,
      showCount: 0,
      transformX: 0
    };
    this.prev = this.prev.bind(this);
    this.next = this.next.bind(this);
    this.handlerIndex = this.hanlderIndex.bind(this);
    this.$emit = this.$emit.bind(this);
    this.getWidth = this.getWidth.bind(this);
    this.changeTransformX = this.changeTransformX.bind(this);
  }
  static propTypes = {
    items: propTypes.array.isRequired,
    transition: propTypes.number,
    dirChange: propTypes.bool,
    onchange: propTypes.func
  };
  static defaultProps = {
    transition: 500,
    dirChange: true,
    onchange: () => {}
  };
  prev() {
    let index = this.state.index;
    index = index <= 0 ? this.props.items.length - 1 : --index;
    this.setState(
      {
        index
      },
      () => {
        this.changeTransformX();
      }
    );
  }
  next() {
    let index = this.state.index;
    index = index >= this.props.items.length - 1 ? 0 : ++index;
    this.setState(
      {
        index
      },
      () => {
        this.changeTransformX();
      }
    );
  }
  hanlderIndex(index) {
    this.setState(
      {
        index
      },
      () => {
        this.changeTransformX();
      }
    );
  }
  changeTransformX() {
    let transformX = 0;
    const props = this.props;
    const state = this.state;
    let index = state.index;
    let itemsLen = props.items.length;
    if (index < state.showCount) {
      transformX = 0;
    } else if (index >= itemsLen - state.showCount) {
      transformX = -itemsLen * 100 + state.wrapWidth;
    } else if (index >= state.showCount) {
      transformX = -(index - state.showCount || 1) * 100;
    }
    this.setState(
      {
        transformX
      },
      () => {
        this.$emit("onchange", index);
      }
    );
  }
  $emit(event, msg) {
    if (!event && event !== 0) return new Error("event不能为空");
    return this.props[event](msg);
  }
  getWidth(ele, attr) {
    return parseFloat(getComputedStyle(ele)[attr]);
  }
  render() {
    const props = this.props;
    const state = this.state;
    let styleWrap = {
      display: "flex",
      width: props.items.length * 100 + "px",
      transition: `all ${props.transition / 1000}s ease`,
      transform: `translateX(${state.transformX}px)`
    };
    return (
      <div style={{ display: "flex", width: "100%", height: "100%" }}>
        {props.dirChange ? (
          <div
            className="pre dir"
            style={{ marginRight: "10px" }}
            onClick={this.prev}
          >
            &lt;
          </div>
        ) : (
          ""
        )}
        <div
          className="items"
          style={{ flex: 1, height: "100%", overflowY: "auto" }}
          ref="wrap"
        >
          <ul className="item" style={styleWrap}>
            {props.items.map((item, i) => (
              <li
                className={i === state.index ? "active" : ""}
                style={{
                  width: "100px",
                  height: "100%",
                  background: "rgba(0, 0, 0, .5)",
                  marginRight: "10px",
                  cursor: "pointer"
                }}
                onClick={this.hanlderIndex.bind(this, i)}
                key={i}
              >
                <img
                  src={item.src}
                  alt=""
                  style={{ width: "100%", height: "95%" }}
                />
                <p style={{ textAlign: "center" }}>{item.title}</p>
              </li>
            ))}
          </ul>
        </div>
        {props.dirChange ? (
          <div
            className="next dir"
            style={{ marginLeft: "10px" }}
            onClick={this.next}
          >
            &gt;
          </div>
        ) : (
          ""
        )}
      </div>
    );
  }
  componentDidMount() {
    let wrapWidth = this.getWidth(this.refs.wrap, "width");
    let showCount = Math.round(wrapWidth / 100 / 2);
    this.setState({
      wrapWidth,
      showCount
    });
  }
}

// vue/src/components/carousel-slider/index.vue
<template>
  <div style="display:flex; width: 100%; height: 100%;">
    <div
      class="pre dir"
      style="margin-right: 10px;"
      @click="index = index <= 0 ? items.length - 1 : --index"
      v-if="dirChange"
    >
      &lt;
    </div>
    <div class="items" style="flex: 1;height: 100%;overflow-y: auto" ref="wrap">
      <ul
        class="item"
        style="display:flex;"
        :style="{
          width: items.length * 100 + 'px',
          transition: `all ${transition / 1000}s ease`,
          transform: `translateX(${transformX}px)`
        }"
      >
        <li
          v-for="(item, i) of items"
          :key="i"
          style="width: 100px;height: 100%;background: rgba(0, 0, 0, .5);margin-right: 10px;cursor: pointer"
          :class="{ active: i === index }"
          @click="index = i"
        >
          <img :src="item.src" alt="" style="width: 100%; height: 95%" />
          <p style="text-align: center">{{ item.title }}</p>
        </li>
      </ul>
    </div>
    <div
      class="next dir"
      style="margin-left: 10px;"
      @click="index = index >= items.length - 1 ? 0 : ++index"
      v-if="dirChange"
    >
      &gt;
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      index: 0,
      wrapWidth: 0,
      showCount: 0,
      transformX: 0
    };
  },
  props: {
    items: {
      type: Array,
      default: () => []
    },
    transition: {
      type: Number,
      default: 500
    },
    dirChange: {
      type: Boolean,
      default: true
    }
  },
  watch: {
    index(index) {
      if (index < this.showCount) {
        this.transformX = 0;
      } else if (index >= this.items.length - this.showCount) {
        this.transformX = -this.items.length * 100 + this.wrapWidth;
      } else if (index >= this.showCount) {
        this.transformX = -(index - this.showCount || 1) * 100;
      }
      this.$emit("change", index);
    }
  },
  methods: {
    getWidth(ele, attr) {
      return parseFloat(getComputedStyle(ele)[attr]);
    }
  },
  mounted() {
    this.$nextTick(() => {
      this.wrapWidth = this.getWidth(this.$refs.wrap, "width");
      this.showCount = Math.round(this.wrapWidth / 100 / 2);
    });
  }
};
</script>

<style lang="scss">
ul {
  padding: 0;
  margin: 0;
  li {
    list-style: none;
    padding: 0;
    margin: 0;
  }
}
p {
  margin: 0;
}
.dir {
  width: 40px;
  height: 100%;
  background: dodgerblue;
  border-radius: 5px;
  color: #fff;
  font-size: 25px;
  text-align: center;
  line-height: 3;
  cursor: pointer;
}
.items {
  .item {
    .active {
      background: transparent !important;
    }
  }
}
.items::-webkit-scrollbar {
  display: none;
}
</style>
