// vue/src/views/carousel-slider/index.vue
<template>
  <div style="width: 700px;height: 80px;margin: auto;">
    <slider :items="items" />
  </div>
</template>

<script>
import Slider from "@components/carousel-slider";
import items from "./items";
export default {
  data() {
    return {
      items
    };
  },
  methods: {},
  components: {
    Slider
  }
};
</script>

// react/src/views/carousel-slider/index.jsx
import CarouseSlider from "../../components/carousel-slider";
import React from "react";
import items from './items';

export default class App extends React.Component {
  constructor() {
    super();
    this.state = {};
  }
  componentDidMount() {
    
  }
  render() {
    return (
      <div style={{width: '800px', margin: '20px auto'}}>
        <CarouseSlider items={items} ></CarouseSlider>
      </div>
    );
  }
}
