// vue/src/views/carousel/index.vue
<template>
  <div style="width: 800px; margin: auto">
    <carousel :items="items" :hide-dir="false" />
  </div>
</template>

<script>
import items from "@components/carousel/items";
import Carousel from "@components/carousel";
export default {
  data() {
    return {
      items
    };
  },
  components: {
    Carousel
  }
};
</script>

// react/src/views/carousel/index.jsx
import Carousel from '../../components/carousel';
import React from "react";
import items from './items';
export default class App extends React.Component {
    render() {
        return (
            <div style={{height: '450px', width: '800px', margin: 'auto'}}>
                <Carousel items={items} />
            </div>
        )
    }
}
